<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INBLRNB0299" ignored="1" name="testcase1" tests="6" failures="1" timestamp="02 Nov 2019 07:34:21 GMT" time="1.06" errors="0">
  <testcase name="f1" time="0.005" classname="testng_samepl.Testng_TestCase1"/>
  <testcase name="f2" time="0.003" classname="testng_samepl.Testng_TestCase1"/>
  <testcase name="f3" time="0.002" classname="testng_samepl.Testng_TestCase1"/>
  <testcase name="f4" time="0.002" classname="testng_samepl.Testng_TestCase1"/>
  <testcase name="f6" time="0.001" classname="testng_samepl.Testng_TestCase1"/>
  <testcase name="f7" time="1.008" classname="testng_samepl.Testng_TestCase1">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testng_samepl.Testng_TestCase1.f7() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testng_samepl.Testng_TestCase1.f7() didn't finish within the time-out 1000
at java.lang.Thread.interrupt0(Native Method)
at java.lang.Thread.interrupt(Thread.java:926)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- f7 -->
  <testcase name="f5" time="0.0" classname="testng_samepl.Testng_TestCase1">
    <ignored/>
  </testcase> <!-- f5 -->
</testsuite> <!-- testcase1 -->
