<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="INBLRNB0299" name="testngsnippet.TestNgTestCase1" tests="7" failures="0" timestamp="22 May 2019 03:17:07 GMT" time="1.017" errors="1">
  <testcase name="f1" time="0.005" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f4" time="0.002" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f3" time="0.001" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f6" time="0.001" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f2" time="0.001" classname="testngsnippet.TestNgTestCase1"/>
  <testcase name="f7" time="1.007" classname="testngsnippet.TestNgTestCase1">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngsnippet.TestNgTestCase1.f7() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngsnippet.TestNgTestCase1.f7() didn't finish within the time-out 1000
at java.lang.Thread.currentThread(Native Method)
at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(Unknown Source)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(Unknown Source)
at java.util.concurrent.locks.ReentrantLock.unlock(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- f7 -->
  <testcase name="f5" classname="testngsnippet.TestNgTestCase1">
    <skipped/>
  </testcase> <!-- f5 -->
</testsuite> <!-- testngsnippet.TestNgTestCase1 -->
