<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17953" started-at="2019-11-03T06:17:51Z" finished-at="2019-11-03T06:18:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17953" started-at="2019-11-03T06:17:51Z" finished-at="2019-11-03T06:18:09Z">
      <class name="testng_samepl.AddNewPayeeScenarioWithDataProvider">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="beforeClass" is-config="true" duration-ms="13496" started-at="2019-11-03T06:17:51Z" finished-at="2019-11-03T06:18:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="beforeMethod" is-config="true" duration-ms="72" started-at="2019-11-03T06:18:05Z" finished-at="2019-11-03T06:18:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test1(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="test1" duration-ms="2210" started-at="2019-11-03T06:18:05Z" data-provider="dp" finished-at="2019-11-03T06:18:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Prem Kumar]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Bangalore]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[234845646]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Brother]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Payee Name not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Payee Name not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at testng_samepl.AddNewPayeeScenarioWithDataProvider.test1(AddNewPayeeScenarioWithDataProvider.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-11-03T06:18:07Z" finished-at="2019-11-03T06:18:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="beforeMethod" is-config="true" duration-ms="76" started-at="2019-11-03T06:18:07Z" finished-at="2019-11-03T06:18:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test1(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="test1" duration-ms="2081" started-at="2019-11-03T06:18:07Z" data-provider="dp" finished-at="2019-11-03T06:18:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Somi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mangalore]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[89789458]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Friend]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Payee Name not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Payee Name not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at testng_samepl.AddNewPayeeScenarioWithDataProvider.test1(AddNewPayeeScenarioWithDataProvider.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="afterClass" is-config="true" duration-ms="0" started-at="2019-11-03T06:18:09Z" finished-at="2019-11-03T06:18:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testng_samepl.AddNewPayeeScenarioWithDataProvider@6d4b1c02]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-11-03T06:18:09Z" finished-at="2019-11-03T06:18:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testng_samepl.AddNewPayeeScenarioWithDataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
